# https://taskfile.dev
---
version: "3"

tasks:
  stow:
    deps:
      - stow-zsh
      - stow-shell

  stow-zsh:
    cmd: stow -t "$HOME" -R zsh

  stow-shell:
    vars:
      DIR: "${HOME}/.config"
    cmds:
      - mkdir -p "{{.DIR}}"
      - stow -t "{{.DIR}}" -R shell

  setup:
    cmds:
      - ./setup/install-packages.sh
    preconditions:
      - sh: test "$(whoami)" = "root"
        msg: Task 'setup' must be run as root!
