# https://taskfile.dev
---
version: "3"

tasks:
  stow:
    deps:
      - stow-zsh
      - stow-config

  stow-zsh:
    cmd: stow -t "$HOME" -R zsh

  stow-config:
    vars:
      CONFIG_DIR: "${HOME}/.config"
      STOW_DIRS:
        sh: for folder in config/*; do basename "$folder"; done
    cmds:
      - mkdir -p "{{.CONFIG_DIR}}"
      - for:
          var: STOW_DIRS
        cmd: mkdir -p "{{.CONFIG_DIR}}/{{.ITEM}}"
      - for:
          var: STOW_DIRS
        cmd: stow -d config -t "{{.CONFIG_DIR}}/{{.ITEM}}" -R {{.ITEM}}

  stow-hyprland:
    vars:
      CONFIG_DIR: "${HOME}/.config"
      STOW_DIRS:
        - hyde
        - hypr
    cmds:
      - mkdir -p "{{.CONFIG_DIR}}"
      - for:
          var: STOW_DIRS
        cmd: mkdir -p "{{.CONFIG_DIR}}/{{.ITEM}}"
      - for:
          var: STOW_DIRS
        cmd: stow -d hyprland -t "{{.CONFIG_DIR}}/{{.ITEM}}" -R {{.ITEM}}
