# Configuration file for HyDE
# Environment variables should be on top
# Updated config.toml file can be found at $HOME/.local/share/hyde/config.toml
"$schema" = "https://raw.githubusercontent.com/HyDE-Project/HyDE/refs/heads/master/Configs/.local/share/hyde/schema/config.toml.json"

[hyprland]
bar = "waybar"
browser = "firefox"
color_scheme = "prefer-dark"
editor = "nvim"
explorer = "Yazi"
font = "FiraCode Nerd Font"
font_size = 12
monospace_font = "FiraCode Nerd Font"
monospace_font_size = 12
quickapps = "ghostty"
terminal = "ghostty"

[notification]
font = "FiraCode Nerd Font"
font_size = 12

[rofi]
scale = 12
